# Generated by Django 4.0.1 on 2022-02-01 14:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={},
        ),
        migrations.AddField(
            model_name='students',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
