# Generated by Django 4.0.1 on 2022-02-02 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentbulkupload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ('name', 'family')},
        ),
    ]
