# Generated by Django 4.0.1 on 2022-02-05 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_students_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ('-id', 'family')},
        ),
    ]
