# Generated by Django 4.0.1 on 2022-02-06 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0002_parents_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parents',
            options={'ordering': ['-id']},
        ),
    ]
